cmake_minimum_required(VERSION 3.21.7)

# Default configs
#set(CMAKE_CONFIGURATION_TYPES Dev Rel)
set(CMAKE_SIZEOF_VOID_P 8)
set(CMAKE_BUILD_TYPE Debug)

set(PROJECT_PLATFORM "Win64")

if(NOT ${CMAKE_BUILD_TYPE} STREQUAL "")
    set(CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE})
else()
    set(CMAKE_BUILD_TYPE Rel)
endif()

if(CMAKE_GENERATOR_PLATFORM STREQUAL "Win32")
    set(PROJECT_PLATFORM "Win32")
    set(CMAKE_SIZEOF_VOID_P 4)
endif()

message("Generating project files for ${PROJECT_PLATFORM} platform.")

set(PROJECT_OUT_DIR ${PROJECT_OUT_DIR}/${PROJECT_PLATFORM}/${CMAKE_BUILD_TYPE})
set(PROJECT_INTERMEDIATE_DIR ${PROJECT_INTERMEDIATE_DIR}/${PROJECT_PLATFORM}/${CMAKE_BUILD_TYPE})
message("Project Output directory is ${PROJECT_OUT_DIR}.")
if(WIN32)
    message("Generating for windows")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_OUT_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_OUT_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PROJECT_OUT_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${PROJECT_OUT_DIR})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PROJECT_OUT_DIR})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${PROJECT_OUT_DIR})
else()
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_OUT_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_OUT_DIR})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_OUT_DIR})
endif()
