cmake_minimum_required(VERSION 3.21.7)

set(GIT_REPO_NAME "Snowflake")
set(PROJECT_PREFIX ${GIT_REPO_NAME}_)
set(PROJECT_NAME ${GIT_REPO_NAME})
set(PROJECT_TEMP_DIR ${CMAKE_SOURCE_DIR}/temp)
set(PROJECT_INTERMEDIATE_DIR ${PROJECT_TEMP_DIR})
set(PROJECT_OUT_DIR ${CMAKE_SOURCE_DIR}/Output)
set(PROJECT_CMAKE_MODULE_DIR ${CMAKE_SOURCE_DIR}/cmake_modules)