cmake_minimum_required(VERSION 3.21.7)

set(PROJECT_PREFIX ${PROJECT_GIT_REPO_NAME}_)
set(PROJECT_CMAKE_MODULE_DIR ${CMAKE_SOURCE_DIR}/cmake_modules)

set(PROJECT_TEMP_DIR ${PROJECT_BINARY_DIR}/temp)
set(PROJECT_INTERMEDIATE_DIR ${PROJECT_TEMP_DIR})
set(PROJECT_OUT_DIR ${PROJECT_BINARY_DIR}/output)
