cmake_minimum_required(VERSION 3.25.0)

include_src(additional_types.h)
include_src(hashed_string.h)
include_src(hashed_string.cc)
include_src(message_handler_interface.h)
include_src(messaging_system.h)
include_src(messaging_system.cc)
include_src(object_controller_interface.h)
include_src(rtti.h)
include_src(rtti.cc)
include_src(shared_pointer.h)
include_src(shared_pointer.cc)
include_src(string_pool.h)
include_src(string_pool.cc)
include_src(string_util.h)
include_src(string_util.cc)
include_src(time_helper.h)
include_src(time_helper.inl)
include_src(unique_ptr.h)
include_src(unique_ptr.cc)
include_src(defs.h)

group_sources(Common)
