#ifndef ENGINE_COMMON_DEFS_H
#define ENGINE_COMMON_DEFS_H

#define ENGINE_STRINGIZE_MACRO_(X) #X
#define ENGINE_STRINGIZE_MACRO(X) ENGINE_STRINGIZE_MACRO_(X)

#ifndef ENGINE_SHADER_DIR
#define ENGINE_SHADER_DIR ""
#endif

#endif