cmake_minimum_required(VERSION 3.25.0)

include_src(client.h)
include_src(client.cc)
include_src(network_manager.h)
include_src(network_manager.cc)
include_src(network_player.h)
include_src(network_player.cc)
include_src(server.h)
include_src(server.cc)
group_sources(Networking)