cmake_minimum_required(VERSION 3.25.0)

include_src(reverse_to_make_equal.h)
include_src(passing_year_books.h)
include_src(rotational_cipher.h)
include_src(zip_link_list.h)
include_src(max_substring_length.h)
include_src(revenue_milestones.h)
include_src(count_triangles.h)
include_src(list.h)
group_sources(/Others)