cmake_minimum_required(VERSION 3.25.0)

include_src(affine_transform.h)
include_src(affine_transform.cc)
include_src(axis_aligned_bounding_box.h)
include_src(bounding_box.h)
include_src(bounding_box.cc)
include_src(math_util_funcs.h)
include_src(math_util_funcs.cc)
include_src(math.h)
include_src(math.cc)
include_src(matrix_4x4.h)
include_src(matrix_4x4.cc)
include_src(quaternion.h)
include_src(quaternion.cc)
include_src(ray_intersection.h)
include_src(ray_intersection.cc)
include_src(triangle.h)
include_src(triangle.cc)
include_src(vector2.h)
include_src(vector2.cc)
include_src(vector3.h)
include_src(vector3.cc)
include_src(vector4.h)
include_src(vector4.cc)
group_sources(Maths)