cmake_minimum_required(VERSION 3.21.7)

include_src(camera.h)
include_src(camera.cc)
include_src(frame_time.h)
include_src(frame_time.cc)    
include_src(mesh_object.h)
include_src(mesh_object.cc)
include_src(object_interface.h)
include_src(scene.h)
include_src(scene.cc)
group_sources(Common/Gfx/DX12)
