cmake_minimum_required(VERSION 3.21.7)

set(PROJECT_PREFIX ${PROJECT_GIT_REPO_NAME}_)
set(PROJECT_CMAKE_MODULE_DIR ${CMAKE_SOURCE_DIR}/cmake)
set(PROJECT_SRC_DIR ${CMAKE_SOURCE_DIR}/source)
set(EXTERNAL_SOURCE_DIR ${CMAKE_SOURCE_DIR}/external)

set(PROJECT_TEMP_DIR ${PROJECT_BINARY_DIR}/tmp)
set(PROJECT_INTERMEDIATE_DIR ${PROJECT_TEMP_DIR})
set(PROJECT_OUT_DIR ${CMAKE_SOURCE_DIR}/${PROJECT_TEMP_DIR}/output)
set(PROJECT_VS_SOLUTION_FOLDER "")

set(DEFAULT_C_COMPILER "C:\\Program\ Files\\LLVM\\bin\\clang.exe")
set(DEFAULT_CXX_COMPILER "C:\\Program\ Files\\LLVM\\bin\\clang++.exe")
set(DEFAULT_CXX_STANDARD 20)
